Module1 task2
htmlacademy-php/1693271-yeticave-12 pull request #12
Opened 2021-05-21 04:10 UTC by Ilgiz-ssg

2021-05-21 07:03 UTC, akabirov commented
Ильгиз, в первом commit было верное исправление, а во втором сделан откат к предыдущему состоянию. Т.е. в итоге ничего не изменилось.

2021-05-21 07:13 UTC, Ilgiz-ssg commented
Добрый день, странно я откат не делал, сейчас исправлю 
 
 
С уважением,
Ильгиз Ямалеев
***@***.***
 
 
  
>Пятница, 21 мая 2021, 10:03 +03:00 от akabirov ***@***.***>:
> 
> 
>Ильгиз, в первом commit было верное исправление, а во втором сделан откат к предыдущему состоянию. Т.е. в итоге ничего не изменилось.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 

2021-05-21 10:48 UTC, akabirov commented
В commit a08e12c3f28643a578f415403d73c8e2eaa21a61 начато внесение изменений.
А в commit 718d575dac34824d4b5cb06130a6a70a5864bb67 (который после него) происходит откат состояния.

2021-05-25 05:13 UTC, akabirov requested changes
Ильгиз!
Почти всё правильно. Но есть одно НО. 
Файл index.php, строка 33
`<p> <?php echo '$user_name' ?> </p>`
Переменная $user_name не должна быть в кавычках! Иначе так и будет отображаться как написано.

И поправка по оформлению кода: после `if, while, for, foreach` и др. команд, перед скобкой ставится пробел. Это правила оформления.

2021-05-25 05:24 UTC, akabirov requested changes
Заметил еще одну промах. Который требуется соблюдать - это отступы!
HTML и PHP при оформлении используют отступы. Рекомендуется для след.уровня отступ в 4 пробела (посмотри примеры в учебнике). 
В нашем же случае, оператор if (все три его части) расползлись по горизонтали ...
Содержание HTML-части тоже. Например содержание <div> должно идти со стандартным  отступом.
Эту часть тоже надо поправить.

2021-05-25 08:38 UTC, akabirov commented
Сейчас почти нормально. Почти, потому-что все строчки добавленного блока if .. (в целом) смещены не на одну табуляцию внутрь, а на 2. Это мы поправим, когда будем переносить код в шаблон.
Эту задание принимаю.
Работаем дальше.

2021-05-25 09:03 UTC, merged

2021-05-25 09:08 UTC, akabirov commented
Ильгиз!
Я проверял изменённую часть файла и не сразу обратил внимание, что куда-то делась изначально заданная часть.
Сам внёс корректировки, при общении объясню.
Пока принял **Работа с условиями**, но нужно будет пообщаться вживую. Сегодня, завтра - этот файл разберём ещё.
Если готовы - заявите консультацию.